batch_size = 32
stack_size = 1
do_profile = false
num_epochs = 20
debug_mode = false
display = "dashboard"
regressor = "mace"
task = "e_form"

[data]
dataset_name = "mptrj"
raw_data_folder = "data"
data_folder = "precomputed"
shuffle_seed = 1618
train_split = 30
test_split = 3
valid_split = 3
batches_per_group = 0
batch_n_nodes = 1024
k = 16
batch_n_graphs = 32

[cli]
verbosity = "info"
show_progress = true

[device]
device = "gpu"
max_gpus = 0
gpu_ids = []

[log]
log_dir = "logs"
logs_per_epoch = 8
epochs_per_ckpt = 2
epochs_per_valid = 2

[train]
lr_schedule_kind = "cosine"
start_lr_frac = 0.1
base_lr = 0.004
end_lr_frac = 0.04
weight_decay = 0.03
beta_1 = 0.9
beta_2 = 0.999
nestorov = true
max_grad_norm = 3.0
schedule_free = false
prodigy = false

[mace]
num_basis = 8
r_max = 6
avg_num_neighbors = 14
max_ell = 3
hidden_irreps = [ "128x0e + 64x1o + 32x2e", "128x0e + 64x1o + 32x2e",]
node_out_dim = 64
interaction_reduction = "last"
share_species_embed = true

[train.loss]
energy_weight = 1
force_weight = 0.1
stress_weight = 0.1

[mace.head]
inner_dims = []
activation = "swish"
final_activation = "Identity"
dropout = 0.0
residual = false
num_heads = 1

[train.loss.reg_loss]
loss_delta = 0.015625
use_rmse = false
