batch_size = 64
do_profile = false
num_epochs = 100
regressor = "vit"
task = "e_form"

[data]
dataset_name = "jarvis_dft3d_cleaned"
raw_data_folder = "data"
data_folder = "precomputed"
shuffle_seed = 1618
train_split = 21
test_split = 2
valid_split = 2
do_augment = false
augment_seed = 12345
so3 = true
o3 = true
t3 = true

[data_transform]
density_power = 0.1111111111111111

[cli]
verbosity = "info"
show_progress = true

[device]
device = "gpu"
max_gpus = 1
gpu_ids = []

[log]
log_dir = "logs"
logs_per_epoch = 8

[train]
lr_schedule_kind = "cosine"
start_lr_frac = 0.1
base_lr = 0.004
end_lr_frac = 0.04
weight_decay = 0.03
beta_1 = 0.9
beta_2 = 0.999
nestorov = true
max_grad_norm = 1.0

[train.loss.reg_loss]
loss_delta = 0.1
use_rmse = false
