batch_size = 64
stack_size = 1
do_profile = false
num_epochs = 4
precision = "f32"
debug_mode = false
display = "progress"
regressor = "mace"
task = "e_form"

[data]
dataset_name = "mptrj"
raw_data_folder = "data"
data_folder = "precomputed"
shuffle_seed = 1618
train_split = 30
test_split = 3
valid_split = 3
batches_per_group = 256
batch_n_nodes = 1024
k = 16
batch_n_graphs = 32

[cli]
verbosity = "info"
show_progress = true

[device]
device = "gpu"
max_gpus = 3
gpu_ids = [0, 1, 2]

[log]
log_dir = "logs"
logs_per_epoch = 32
epochs_per_ckpt = 4
epochs_per_valid = 0.5
tags = ["downsample"]

[train]
lr_schedule_kind = "cosine"
start_lr_frac = 0.01
base_lr = 1
end_lr_frac = 0.5
weight_decay = 0.001
beta_1 = 0.9
beta_2 = 0.999
nestorov = false
max_grad_norm = 3.0
schedule_free = false
prodigy = true

[mace]
residual = true
resid_init = "zeros"
outs_per_node = 64
interaction_reduction = "last"
share_species_embed = true

[train.loss]
energy_weight = 1.0
force_weight = 0.0
stress_weight = 0.0

[mace.node_embed]
embed_dim = 64
kind = "linear"

[mace.edge_embed]
r_max = 7.0
r_max_trainable = true
radius_transform = "Identity"

[mace.interaction]
kind = "simple"

[mace.readout]
kind = "linear"

[mace.self_connection]
kind = "s2-mlp-mixer"

[mace.head]
inner_dims = [64, 64]
activation = "silu"
final_activation = "Identity"
dropout = 0.2
residual = false
num_heads = 1
use_bias = true
normalization = "layer"

[mace.hidden_irreps]
kind = "derived"
dim = 384
max_degree = 2
gamma = 1
num_layers = 3
min_gcd = 2

[train.loss.reg_loss]
loss_delta = 0.015625
use_rmse = false

# [mace.edge_embed.radial_basis]
# num_basis = 12
# kind = "bessel"
# freq_trainable = true

[mace.edge_embed.radial_basis]
num_basis = 12
kind = 'gauss'
mu_max = 8.0
sd = 0.34
sd_trainable = true
mu_trainable = true

[mace.edge_embed.envelope]
kind = "exp"
cutoff_start = 0.9
c = 0.1

[mace.interaction.message]
kind = "sevennet-conv"
# kind = "node-feature-mlp-weighted"
avg_num_neighbors = 14.0
max_ell = 4

[mace.self_connection.s2_grid]
activation = "silu"
res_beta = 18
res_alpha = 17
normalization = "integral"
quadrature = "soft"
use_fft = false

[mace.self_connection.mlp]
inner_dims = [32, 32]
activation = "silu"
final_activation = "Identity"
dropout = 0.0
residual = false
num_heads = 2
use_bias = false
normalization = "layer"

[mace.interaction.message.radial_weight]
inner_dims = [32]
activation = "silu"
final_activation = "tanh"
dropout = 0.0
residual = false
num_heads = 1
use_bias = false
normalization = "layer"

# [mace.interaction.message.node_feature_mlp]
# inner_dims = [16]
# activation = "silu"
# final_activation = "tanh"
# dropout = 0.2
# residual = false
# num_heads = 1
# use_bias = true
# normalization = "layer"
