batch_size = 63
do_profile = false
num_epochs = 50
regressor = "mace"
task = "e_form"

[data]
dataset_name = "jarvis_dft3d_cleaned"
raw_data_folder = "data"
data_folder = "precomputed"
shuffle_seed = 1618
train_split = 81
test_split = 2
valid_split = 3
batch_n_nodes = 512
batch_n_edges = 9872
batch_n_graphs = 64

[cli]
verbosity = "info"
show_progress = true

[device]
device = "gpu"
max_gpus = 3
gpu_ids = [0, 1, 2]

[log]
log_dir = "logs"
logs_per_epoch = 8
epochs_per_ckpt = 100
epochs_per_valid = 5

[train]
lr_schedule_kind = "cosine"
start_lr_frac = 0.1
base_lr = 3e-3
end_lr_frac = 0.04
weight_decay = 0.05
beta_1 = 0.9
beta_2 = 0.999
nestorov = true
max_grad_norm = 1.0
schedule_free = false
prodigy = false

[mace]
max_ell = 2
# num_interactions = 5
num_interactions = 5
hidden_irreps = "128x0e + 64x1o + 32x2e"
correlation = 2
readout_mlp_irreps = "128x0e + 64x1o + 32x2e"

[train.loss.reg_loss]
loss_delta = 0.015625
use_rmse = false
