batch_size = 63
do_profile = false
num_epochs = 20
regressor = "mace"
task = "e_form"

[data]
dataset_name = "jarvis_dft3d_cleaned"
raw_data_folder = "data"
data_folder = "precomputed"
shuffle_seed = 1618
train_split = 22
test_split = 2
valid_split = 2
batch_n_nodes = 512
batch_n_edges = 9872
batch_n_graphs = 64

[cli]
verbosity = "info"
show_progress = true

[device]
device = "gpu"
max_gpus = 1
gpu_ids = []

[log]
log_dir = "logs"
logs_per_epoch = 8

[train]
lr_schedule_kind = "cosine"
start_lr_frac = 0.1
base_lr = 0.004
end_lr_frac = 0.04
weight_decay = 0.1
beta_1 = 0.9
beta_2 = 0.999
nestorov = true
max_grad_norm = 1.0
schedule_free = true

[mace]
max_ell = 3
num_interactions = 2
hidden_irreps = "256x0e + 256x1o"
correlation = 2
readout_mlp_irreps = "128x0e + 16x1o"

[train.loss.reg_loss]
loss_delta = 0.015625
use_rmse = false
