batch_size = 256
stack_size = 1
do_profile = false
debug_mode = false
num_epochs = 16
display = "progress"
regressor = "mace"
task = "e_form"

[data]
dataset_name = "mptrj"
shuffle_seed = 1618
train_split = 30
test_split = 3
valid_split = 3
batches_per_group = 0

[cli]
verbosity = "info"
show_progress = true

[device]
device = "gpu"
max_gpus = 3
gpu_ids = [0, 1, 2]

[log]
log_dir = "logs"
logs_per_epoch = 16
epochs_per_ckpt = 4
epochs_per_valid = 0.5
tags = ["test"]
exp_name = "test_lin_sh"

[train]
lr_schedule_kind = "cosine"
start_lr_frac = 0.1
base_lr = 2e-3
end_lr_frac = 0.04
weight_decay = 1e-8
beta_1 = 0.9
beta_2 = 0.99
nestorov = true
max_grad_norm = 3.0
schedule_free = false
prodigy = false


[train.loss]
energy_weight = 1
force_weight = 0
stress_weight = 0

[mace]
hidden_irreps = [
    "128x0e + 64x1e + 32x2e",
    "128x0e + 64x1e + 32x2e",
    "128x0e + 64x1e + 32x2e",
    "128x0e + 64x1e + 32x2e",
]
outs_per_node = 128
interaction_reduction = "last"
share_species_embed = true
residual = true

[mace.node_embed]
embed_dim = 128
kind = "linear"

[mace.interaction]
kind = "simple"

[mace.readout]
kind = "linear"

[mace.self_connection]
kind = "gate"

[mace.head]
inner_dims = [64, 64]
activation = "silu"
final_activation = "Identity"
dropout = 0
residual = false
num_heads = 1

[mace.edge_embed]
r_max = 5
r_max_trainable = false

[mace.edge_embed.radial_basis]
num_basis = 8
kind = "bessel"
freq_trainable = false

[mace.edge_embed.envelope]
kind = "exp"
cutoff_start = 0.9
c = 0.1

[mace.interaction.message]
kind = "sevennet-conv"
avg_num_neighbors = 14
max_ell = 2

[mace.interaction.message.radial_weight]
inner_dims = [64, 64]
activation = "silu"
final_activation = "shifted_softplus"
dropout = 0
residual = false
num_heads = 1
use_bias = false
