batch_size = 256
stack_size = 1
num_epochs = 4
precision = "f32"
debug_mode = true
do_profile = false
display = "progress"

[data]
dataset_name = "mp2022"
raw_data_folder = "data"
data_folder = "precomputed"
shuffle_seed = 29205
train_split = 30
test_split = 3
valid_split = 3
batches_per_group = 0
batch_n_nodes = 1024
k = 16
batch_n_graphs = 32

[log]
log_dir = "logs"
logs_per_epoch = 16
epochs_per_ckpt = 100
epochs_per_valid = 0.5
tags = []

[model]
resid_init = "ones"

[train.loss]
energy_weight = 1
force_weight = 0
stress_weight = 0
