batch_size = 32
stack_size = 1
do_profile = false
debug_mode = true
num_epochs = 10
display = "dashboard"
regressor = "mace"
task = "e_form"

[data]
dataset_name = "mptrj"
shuffle_seed = 1618
train_split = 30
test_split = 3
valid_split = 3
batches_per_group = 50

[cli]
verbosity = "info"
show_progress = true

[device]
device = "gpu"
max_gpus = 3
gpu_ids = [0, 1, 2]

[log]
log_dir = "logs"
logs_per_epoch = 8
epochs_per_ckpt = 2
epochs_per_valid = 2

[train]
lr_schedule_kind = "cosine"
start_lr_frac = 0.1
base_lr = 4e-3
end_lr_frac = 0.04
weight_decay = 1e-8
beta_1 = 0.9
beta_2 = 0.999
nestorov = true
max_grad_norm = 3.0
schedule_free = false
prodigy = false


[train.loss]
energy_weight = 1
force_weight = 0.1
stress_weight = 0.01

[mace]
hidden_irreps = ["128x0e + 64x1o + 32x2e", "256x0e"]
outs_per_node = 64
interaction_reduction = "last"
share_species_embed = true

[mace.node_embed]
embed_dim = 64
kind = "linear"

[mace.interaction]
kind = "simple"

[mace.readout]
kind = "linear"

[mace.self_connection]
kind = "mlp-gate"
num_hidden_layers = 1

[mace.head]
inner_dims = []
activation = "swish"
final_activation = "Identity"
dropout = 0.3
residual = false
num_heads = 1

[mace.edge_embed.radial_basis]
num_basis = 8
r_max = 6
kind = "bessel"
freq_trainable = true

[mace.edge_embed.envelope]
kind = "exp"
cutoff_start = 0.8
c = 1

[mace.interaction.message]
kind = "simple-mix-mlp-conv"
avg_num_neighbors = 14
max_ell = 2

[mace.self_connection.mlp]
inner_dims = []
activation = "swish"
final_activation = "Identity"
dropout = 0
residual = false
num_heads = 1

[mace.interaction.message.radial_mix]
inner_dims = []
activation = "swish"
final_activation = "Identity"
dropout = 0.0
residual = false
num_heads = 1
