batch_size = 64
stack_size = 1
do_profile = false
num_epochs = 10
regressor = "mace"
task = "e_form"

[data]
shuffle_seed = 1618
train_split = 30
test_split = 3
valid_split = 3
batches_per_group = 100

[cli]
verbosity = "info"
show_progress = true

[device]
device = "gpu"
max_gpus = 3
gpu_ids = [0, 1, 2]

[log]
log_dir = "logs"
logs_per_epoch = 16
epochs_per_ckpt = 5
epochs_per_valid = 1
exp_name = "refactor"

[train]
lr_schedule_kind = "cosine"
start_lr_frac = 0.1
base_lr = 1e-3
end_lr_frac = 0.04
weight_decay = 1e-8
beta_1 = 0.9
beta_2 = 0.999
nestorov = true
max_grad_norm = 3.0
schedule_free = false
prodigy = false

[mace]
max_ell = 2
# num_interactions = 5
num_interactions = 2
hidden_irreps = "128x0e"
correlation = 2
readout_mlp_irreps = "128x0e"

[train.loss.reg_loss]
loss_delta = 0.015625
use_rmse = false

[train.loss]
stress_weight = 0.01
force_weight = 0.01
energy_weight = 1
